### ISSUE TITLE
import error when do STAR inference

### ISSUE THREAD

**Issue by yitsingF** [jingtaozhan/DRhard#11]
There is an ImportError when I am trying to replicate your work

```
$python ./star/inference.py --data_type passage --max_doc_length 256 --mode dev
Traceback (most recent call last):
  File "./star/inference.py", line 15, in <module>
    from model import RobertaDot
  File "/home/yicheng.fyc/DRhard/./model.py", line 10, in <module>
    from transformers.modeling_roberta import RobertaPreTrainedModel
ImportError: cannot import name 'RobertaPreTrainedModel' from 'transformers.modeling_roberta' (/home/yicheng.fyc/miniconda2/envs/adore/lib/python3.8/site-packages/transformers-2.8.0-py3.8.egg/transformers/modeling_roberta.py)
```

It happens for both 2.8.0 and 3.4.0 of transformers.
upgrade transformers to 4.2 will fixed this problems but it will leads a huge gap between the MRR index.

**Comment by jingtaozhan** [comment]
Sorry for the late reply. I'm attending SIGIR these days. 
This is not expected. I just tried with version 3.4.0 and it works (fail with version 2.8.0). I think you can print `transformers.__version__' and see whether it is 3.4.0. Let me know what I can do to help.

**Comment by jingtaozhan** [comment]
Although I haven't tried with version 4, there shouldn't be any performance degeneration if you can successfully run the script.
