### ISSUE TITLE
Can not open link of warmup model as ANCE

### ISSUE THREAD

**Issue by ylwangy** [jingtaozhan/DRhard#16]
Hi, jingtao

the link from warmup model of ANCE is invalid?

**Comment by jingtaozhan** [comment]
Which link, specifically?
If you are talking about the warmup model of ANCE, you can download from its repo https://github.com/microsoft/ANCE

**Comment by ylwangy** [comment]
We use the same warmup model as ANCE, the most competitive baseline, to enable a fair comparison. Please download it and extract it at ./data/passage/warmup.

The link of "link" can not be opened, so which ANCE models it refers to ?

**Comment by jingtaozhan** [comment]
Sorry! I forgot adding the link. It has been fixed. You should get a MRR@10 score about 0.31 on msmarco passage ranking using this warmup model. Thank you for identifying this problem.
