### ISSUE TITLE
keyError of rankdict

### ISSUE THREAD

**Issue by ylwangy** [jingtaozhan/DRhard#17]
Hi，jingtao

When I train the STAR model. There exist an error. 

File "./dataset.py", line 176, in __getitem__
    hardpids = random.sample(self.rankdict[str(qid)], self.hard_num)
KeyError: '18337'

The valid keys of rankdict should be 1,2,...,6980. Am I right?

**Comment by jingtaozhan** [comment]
It should be. But in my experiment, JSON automatically convert the int qid to string when I dump the dict in [this line.](https://github.com/jingtaozhan/DRhard/blob/f46691d2514c6b9c61debad90eab03c996e5bd9e/star/prepare_hardneg.py#L70). Therefore, I use the `str(qid)` as the key.

**Comment by ylwangy** [comment]
Oh, I think the mode should be **train** !?

Next, we use this warmup model to extract static hard negatives, which will be utilized by STAR.

python ./star/prepare_hardneg.py \
--data_type passage \
--max_query_length 32 \
--max_doc_length 256 \
--mode **dev** \
--topk 200

**Comment by jingtaozhan** [comment]
Yes, it should be train.
