### ISSUE TITLE
How did you evaluate on trec 2019 test

### ISSUE THREAD

**Issue by jordane95** [jingtaozhan/DRhard#22]
Hi,

I can't find the instruction to replicate the nDCG performance on TREC 19.
Could you tell me how to run the evaluation on TREC 19 test set.

Thanks.

**Comment by jingtaozhan** [comment]
inference.py takes the input of 'mode' argument. Set it to 'test' and you can get the results of TREC 19. 
To evaluate the NDCG metric, you need to use the [trec_eval](https://trec.nist.gov/trec_eval/) tool.
