### ISSUE TITLE
RepBERT

### ISSUE THREAD

**Issue by wangjiajia5889758** [jingtaozhan/DRhard#4]
Is the generating of passage_embeddings of this program the same as the RepBERT program?: 

python precompute.py --load_model_path ./data/ckpt-350000 --task doc
python precompute.py --load_model_path ./data/ckpt-350000 --task query_dev.small
python precompute.py --load_model_path ./data/ckpt-350000 --task query_eval.small

**Comment by jingtaozhan** [comment]
This repo uses the output embedding of [cls] as the query/passage embedding.
RepBERT uses the average token embedding as the query/passage embedding.
The encoder implementation is different.
