### ISSUE TITLE
about the length of tokens

### ISSUE THREAD

**Issue by KaishuaiXu** [jingtaozhan/DRhard#6]
Hello,

I have read your paper and am quite interested in your work! There is a question about the tokens.
I notice you truncat the passage tokens with 120 in MSMARCO Passage Retrieval, however, for ANCE, the original paper uses 512 tokens. So does the number of tokens have the impact on the accuracy?

**Comment by jingtaozhan** [comment]
No
We just don't have that many advanced GPUs to afford very long input :(
BTW, the average passage length is about 70 tokens and truncating to 120 shouldn't be a problem.

**Comment by KaishuaiXu** [comment]
hhhhhhhhha!

Thanks a lot for your reply! I have no multiple GPUs either! Lol!
I agree with your settings!
