### ISSUE TITLE
Questions about Training pipeline

### ISSUE THREAD

**Issue by dhx20150812** [jingtaozhan/DRhard#7]
您好，我在尝试重复您的训练时，发现代码中有关训练的流程并没有文档来说明。请问您是否有时间可以整理一下相关说明文档呢？

**Comment by jingtaozhan** [comment]
Sorry, I'm currently working on another paper that is due next week and don't have time.
I assume the training instructions will be ready next weekend.

**Comment by dhx20150812** [comment]
好的，预祝您论文高中！

**Comment by surajnair04** [comment]
Thanks for releasing the code, @jingtaozhan. 
Any update on when the instructions will be ready?

**Comment by jingtaozhan** [comment]
@surajnair04  I'm at the end of this semester and have several deadlines recently. I'll try to update the instructions.

**Comment by surajnair04** [comment]
@jingtaozhan Apologies for sounding pushy but please take your time.

**Comment by jingtaozhan** [comment]
@surajnair04 It's OK. It's me who should apologize :)

**Comment by ylwangy** [comment]
您好，请问时候有关于训练说明的更新呢?

**Comment by jingtaozhan** [comment]
Very sorry for the delay.
This weekend, I promise.

**Comment by jingtaozhan** [comment]
The training instructions are updated. 
Feel free to open an issue if there are any questions.
