### ISSUE TITLE
Evaluatation on test passage dataset

### ISSUE THREAD

**Issue by staoxiao** [jingtaozhan/DRhard#8]
Hello,
I found the result of proviededi nbatch-neg model on test dataset is so bad. Is TREC DL Passgae data a test dataset?  
What I should do to reproduce the NDCG@10 and R@100 on TREC DL dataset?

- Command:
python ./msmarco_eval.py ./data/passage/preprocess/test-qrel.tsv ./data/passage/evaluate/download_inbatch/test.rank.tsv

- Results:
Eval Started
#####################
MRR @10: 0.04559967102039234
QueriesRanked: 43
#####################

**Comment by jingtaozhan** [comment]
Can you provide more details about how you get the test.rank.tsv? Can you reproduce the results using the provided STAR model?
